defaults:
  - _self_
  - actor: flag_actor
  - critic: crossq_distributional_critic
  - alpha: default
  - optim@_global_: default

seed: 42

# environment parameters
env_id: null
normalize_env: true
normalize_obs: true
normalize_reward: true
normalize_reward_eval: false
normalize_gamma: ${discount}
normalize_clip_obs: 10.0
normalize_clip_reward: 5.0
normalize_eps: 1e-8
normalize_g_max: 5.0
discount: 0.99

# critic parameters
critic_ema_rate: 0.005
ent_coeff: 0.005  # for entropy regularization of distributional critic

# training parameters
total_steps: 1000001
start_steps: 10000
log_interval: 100
eval_interval: 10000
eval_episodes: 5
eta: 0.1
utd: 2
policy_delay: 3
alpha_target_entropy_coeff: -1.0

# FLAG specific parameters
supervision_coef_max: 1.0
supervision_warmup_steps: 100000
supervision_ramp_steps: 100000

logstd_min: -3.0
logstd_scheduler: exponential  # linear std interpolation
logstd_warmup_steps: 200000
logstd_decay_steps: 800000

buffer:
  _target_: flag.buffers.ReplayBuffer
  size: 1000000
  batch_size: 256

guidance_buffer:
  _target_: flag.buffers.GuidanceBuffer
  size: 10240
  batch_size: 256

# WandB (for logging)
wandb:
  entity: ICML2026
  project: flag-humanoid-bench
  mode: online
