_target_: flag.critics.DistributionalCritic
num_networks: 2
has_target: true
use_crossq_trick: false
max_val: 5.0
min_val: -5.0
n_atoms: 101
network_config:
  _target_: flag.utils.nn.MLPConfig
  hidden_features: [256, 256, 256]
  use_batch_renorm: false
